### ISSUE TITLE
[BUG] Not working with SocketIO 2.0 

### ISSUE THREAD

**Issue by iMegaMaximus2** [nkzawa/socket.io-stream#122]
[BUG] Not working with SocketIO 2.0

**Comment by nicoabie** [comment]
Can you post an example?

**Comment by abdolrhman** [comment]
does any  one know an altrantive or a hack to implement it in  ocket io 2.0 ?

**Comment by nicoabie** [comment]
@abdolrhman it is working for me, what kind of issue are you experiencing? 
I'm using socket.io 2.2.0 with socket.io-stream 0.9.1

**Comment by cainiaokan** [comment]
same here

`2019-09-18 14:10:13,382 ERROR 89127 nodejs.TypeError: obj.hasOwnProperty is not a function (uncaughtException throw 1 times on pid:89127)
    at Decoder.decodeObject (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:100:13)
    at Decoder.decode (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:77:17)
    at Decoder.decodeObject (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:101:19)
    at Decoder.decode (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:77:17)
    at Decoder.decodeObject (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:101:19)
    at Decoder.decode (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:77:17)
    at Decoder.decodeObject (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:101:19)
    at Decoder.decode (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:77:17)
    at Decoder.decodeArray (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:92:17)
    at Decoder.decode (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/parser.js:75:17)
    at Socket.onstream (/Users/apple/Code/web-console/node_modules/socket.io-stream/lib/socket.js:183:25)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at Socket.<anonymous> (/Users/apple/Code/web-console/node_modules/component-bind/index.js:21:15)
    at emitThree (events.js:136:13)
    at Socket.emit (events.js:217:7)`

socket.io-stream 0.9.1
socket.io 2.1.1

**Comment by nicoabie** [comment]
@cainiaokan what version of nodejs are you using?

**Comment by cainiaokan** [comment]
@nicoabie Sorry, my bad. Actually it's not socket.io's problem.  We use a nodejs framework called egg.js. It has a plugin system and one of their officially maintained plugin works together with socket.io. However one of the args passed in is abnormal. From what i know, it seems like the argument is created by `Object.create(null)` which does't have a prototype.

**Comment by nicoabie** [comment]
@cainiaokan yeah, that would make sense. If there is no prototype there is no hasOwnProperty function. Do you have a snippet? Also I would create a separare issue here and link it to egg.js plugin.
